Repository OWASP/SecurityShepherd, pull requests merged in 2018-10, with the labels that each got.

#428 #427 Updating Registration UI and User Name Restrictions
  src/main/java/utils/Validate.java
  src/main/webapp/register.jsp
Labels: Bug, Platform

#437 #436 Removing old Registration Validation
  src/main/webapp/register.jsp
Labels: Bug, Platform

#433 #432 Adding Cheat Sheet Entry to DB
  src/main/resources/database/coreSchema.sql
Labels: Bug, Levels

#438 Dev#394
  pom.xml
  src/main/java/servlets/Setup.java
  src/main/resources/database/updatev3_0tov3_1.sql
  src/main/resources/i18n/text.properties
  src/main/webapp/setup.jsp
  src/setupFiles/shepherdTotalInstall.sh
  src/setupFiles/tomcatShepherdSampleServer.xml
  src/setupFiles/tomcatShepherdSampleWeb.xml
  src/setupFiles/updateCoreSchemaV2.4.sql
  src/setupFiles/updateCoreSchemaV2.4toV3.sql
  src/setupFiles/updateModuleSchemasV2.4.sql
Labels: Distribution

#403 Auto Deployment of Security Shepherd
  .env
  .travis.yml
  docker/deploy/push_dev.sh
  docker/deploy/push_master.sh
Labels: Distribution

#442 Added Vagrantfile to automate installation of SecurityShepherd
  Vagrantfile
  provisioning/install.sh
Labels: Distribution

#455 Feature/i18n french
  src/main/resources/i18n/text_fr.properties
  src/main/webapp/translation-select.jsp
Labels: Translation
