Repository OWASP/SecurityShepherd, pull requests merged in 2022-11, with the labels that each got.

#709 Dev#707
  Dockerfile
  docker-compose.yml
Labels: Enhancement

#646 Adding OWASP Dependency-Check GitHub Action
  .github/workflows/dependency-check.yml
Labels: Test Automation, dependencies

#706 Generating SBOMs, Updating Deps and releasing dbs to dockerhub too
  .github/workflows/release.yml
  .github/workflows/test.yml
  pom.xml
Labels: Enhancement, Distribution, dependencies
